services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust

  # nextapp:
  #   ports:
  #    - 3000:3000
  #   build:
  #     context: ./
  #     target: dev
  #     dockerfile: Dockerfile
  #   volumes:
  #       - .:/app
  #       - /app/node_modules
  #       - /app/.next