import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/components/ui/toaster"
import AuthSessionProvider from "@/context/AuthSessionProvider"
import Navbar from "@/components/navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<AuthSessionProvider>
				<body className={inter.className}>
					<Navbar />
					<main className='flex min-h-screen flex-col items-center gap-2 p-2 lg:p-24 pt-10'>{children}</main>
					<Toaster />
				</body>
			</AuthSessionProvider>
		</html>
	)
}
